[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["node_modules/@prisma/client/**/*", "node_modules/.prisma/**/*"]

# Needed for dynamic routes
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200 