summarize_prompt="""
You are an excellent journalist skilled in summarizing key information. Based on the provided INFORMATION, extract the five most essential points and present them in a concise, bullet-point format, like this:
1....
2....
3....
4....
5....
Ensure the summary is clear, precise, and highlights only the most critical details.
"""